argument_specs:
  main:
    short_description: Install and configure Visual Studio Code on a linux distribution
    author: Spartan0nix
    options:
      vscode_extensions:
        type: list
        elements: str
        required: false
        default: []
        description: The list of vscode extensions to install
