---
- name: Install 'python' packages # noqa: package-latest
  ansible.builtin.pip:
    name:
      - ansible-lint
      - molecule
      - "molecule-plugins[docker]"
      - antsibull-docs
    state: latest
