- name: Delete
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete the containers
      community.docker.docker_container:
        name: "{{ molecule.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: molecule
        label: "{{ molecule.name }}"

    - name: Delete the network
      community.docker.docker_network:
        name: dotfiles_molecule
        state: absent
