global_requirements_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - man
  - net-tools
  # - software-properties-common
  - python3-debian
  - sshpass
  - vim
  - wget
  - which
