argument_specs:
  main:
    short_description: Install and configure Kubectl on a linux distribution
    author: Spartan0nix
    options:
      kubectl_shell_completion:
        type: list
        elements: str
        required: false
        default:
          - zsh
        choices:
          - bash
          - zsh
        description: The list of shell to configure auto completion for.
