---
argument_specs:
  main:
    short_description: Install and configure NodeJS on a linux distribution
    author: Spartan0nix
    options:
      nodejs_nvm_version:
        type: str
        required: false
        default: master
        description:
          - C(Branch) or C(tag) used to clone the Nvm Git repository.
          - See "https://github.com/nvm-sh/nvm".
